; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:receiver]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = waveshare_rp2040_zero
framework = arduino
board_build.core = earlephilhower
lib_deps =
    adafruit/Adafruit_VL53L0X @ ^1.2.4
build_flags = 
    -std=gnu++2a ; Forces C++20 standard
    -O0
monitor_speed = 115200
monitor_echo = yes
monitor_filters = send_on_enter
build_src_filter = +<receiver.cpp>
                   +<stepper.cpp>

[env:transmitter]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = waveshare_rp2040_zero
framework = arduino
board_build.core = earlephilhower
lib_deps =
    adafruit/Adafruit_VL53L0X @ ^1.2.4
build_flags = 
    -std=gnu++2a ; Forces C++20 standard
monitor_speed = 115200
monitor_echo = yes
monitor_filters = send_on_enter
build_src_filter = +<transmitter.cpp>

[platformio]
default_envs = transmitter

