; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:receiver]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = waveshare_rp2040_zero
framework = arduino
board_build.core = earlephilhower
build_src_filter = +<receiver.cpp>
lib_deps =
    https://github.com/Fhilb/DW3000_Arduino.git
    adafruit/Adafruit_VL53L0X @ ^1.2.4
build_flags = 
    -std=gnu++2a ; Forces C++20 standard
monitor_speed = 115200
